name: Build k8s-manifests

on:
  push:
    branches: [ main ]

concurrency:
  group: build-k8s-manifests
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
  HAB_LICENSE: accept-no-persist


jobs:
  build-k8s-manifests:
    runs-on: ubuntu-latest
    steps:

    - name: 'Update holobranch: releases/k8s-manifests'
      uses: JarvusInnovations/hologit@actions/projector/v1
      with:
        holobranch: k8s-manifests-github
        commit-to: releases/k8s-manifests
